name: thcdeployment

on:
  push:
    branches: [ main ]

jobs:
  todo:
      runs-on: "ubuntu-latest"
      steps:
        - uses: "actions/checkout@master"
        - name: "TODO to Issue"
          uses: "alstr/todo-to-issue-action@v4.5.3"
          id: "todo"
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      
      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/{%s answer2 %}:latest .
      - name: Push
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/{%s answer2 %}:latest
      - name: Deploy
        run: |
          gcloud run deploy {%s answer2 %} \
          --port {%s answer3 %} \
          --region {%s answer4 %} \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/{%s answer2 %} \
          --platform managed \
          --{%s answer5 %} \
          --quiet \
          --project ${{ secrets.GCP_PROJECT_ID }}

   